#!/usr/bin/env python3
"""Fail if any Markdown file links to a heading anchor that does not exist.

This gate exists because the same bug shipped twice in one review topic: a
section in `docs/ci-cd.md` was retitled and the `#…` fragment naming it went
stale in three places. The first manual sweep found two, because its scope was
*the file being retitled*, and a cross-file reference is exactly what a scoped
sweep cannot see.

The gate's own failure mode is worse than the bug it catches. A checker that
does not understand a construct prints "all resolve", which is
indistinguishable from a clean repository -- so a regression does not go red,
it goes quietly green. Two hand-rolled versions of this file did precisely
that, between them, for: non-ASCII fragments, links with titles, angle-bracket
and escaped destinations, reference-style links, headings inside fenced code,
headings inside HTML comments, illegal fence info strings, HTML entities, and
emoji. The emoji case is the one that settles the argument -- `## Emoji 🚀
test` is not exotic, github-slugger produces `emoji--test`, and the second
hand-rolled slug produced `emoji-🚀-test`, so a broken link passed and a
working one failed.

So neither half is hand-rolled any more:

* **Structure** comes from `markdown_it` (CommonMark). Headings, fenced code,
  HTML blocks, entity decoding, backslash escapes, and reference-link
  resolution are the parser's job, and it is a solved problem.
* **Slugs** come from `_github_slugger_table.py`, generated by
  `scripts/vendor_github_slugger.py` by running github-slugger's own regex
  over every code point. The vendored file records the upstream version and
  the sha256 of the two source files it was produced from.

github-slugger's algorithm is three steps -- lowercase, delete every character
in that set, replace each remaining space with a hyphen (one per space, never
per run) -- plus the `-1`/`-2` suffixes it appends when a slug repeats, which
are tracked here in document order the same way.

Remaining known divergence, stated rather than implied: `str.lower()` and
JavaScript's `toLowerCase()` disagree on a handful of code points. No heading
in this repository is affected, and the differential corpus in
tests/unit/test_check_doc_anchors.py pins the cases that are testable here.

Usage: scripts/check_doc_anchors.py  (exit 0 clean, 1 with findings)
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from urllib.parse import unquote

from markdown_it import MarkdownIt

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _github_slugger_table import REMOVED_RANGES  # noqa: E402

REMOVED = {cp for lo, hi in REMOVED_RANGES for cp in range(lo, hi + 1)}


def slug(text: str) -> str:
    """github-slugger's `slug()`: lowercase, drop, then one hyphen per space."""
    lowered = text.lower()
    kept = "".join(ch for ch in lowered if ord(ch) not in REMOVED)
    return kept.replace(" ", "-")


def _parser() -> MarkdownIt:
    # "commonmark" preset: no GFM extensions that would invent structure the
    # renderer on GitHub does not produce for these files.
    return MarkdownIt("commonmark")


def _inline_text(token) -> str:
    """The rendered text of a heading, as GitHub would slug it.

    Entities and escapes are already resolved by the parser; inline code keeps
    its content; raw HTML tags contribute nothing, matching github-slugger's
    own tag stripping.
    """
    parts: list[str] = []
    for child in token.children or []:
        if child.type in {"text", "code_inline"}:
            parts.append(child.content)
        elif child.type == "softbreak" or child.type == "hardbreak":
            parts.append(" ")
    return "".join(parts)


def anchors_of(tokens) -> set[str]:
    """Every fragment GitHub would generate, including its -1/-2 sequence.

    This mirrors github-slugger's `GithubSlugger.slug`, which does not simply
    count occurrences: it increments until the candidate is *unoccupied*. The
    difference is not academic. For headings `Foo`, `Foo-1`, `Foo`, counting
    yields `foo`, `foo-1`, `foo-1` -- a collision that hides one real anchor
    and invents a duplicate. GitHub yields `foo`, `foo-1`, `foo-2`. The
    differential corpus caught exactly this in the first draft of this file.
    """
    occurrences: dict[str, int] = {}
    anchors: set[str] = set()
    for i, token in enumerate(tokens):
        if token.type != "heading_open":
            continue
        base = slug(_inline_text(tokens[i + 1]))
        if not base:
            continue
        result = base
        while result in occurrences:
            occurrences[base] += 1
            result = f"{base}-{occurrences[base]}"
        occurrences[result] = 0
        anchors.add(result)
    return anchors


def _walk(tokens):
    for token in tokens:
        yield token
        if token.children:
            yield from _walk(token.children)


def links_of(tokens) -> list[str]:
    """Destinations of every live link, with reference links already resolved.

    Unused reference *definitions* are deliberately absent: the parser only
    emits a link token where a link is actually rendered, so a stale
    definition nobody uses no longer produces a finding.
    """
    return [
        token.attrGet("href") or ""
        for token in _walk(tokens)
        if token.type in {"link_open", "image"}
    ]


def tracked_markdown(root: Path) -> list[Path]:
    out = subprocess.run(
        ["git", "ls-files", "*.md"], cwd=root, capture_output=True, text=True, check=True
    )
    return [root / line for line in out.stdout.splitlines() if line]


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    md = _parser()
    files = tracked_markdown(root)
    parsed = {f.resolve(): md.parse(f.read_text(encoding="utf-8")) for f in files}
    anchors = {path: anchors_of(tokens) for path, tokens in parsed.items()}

    problems: list[str] = []
    checked = 0
    for f in files:
        for href in links_of(parsed[f.resolve()]):
            if "#" not in href:
                continue
            target, _, fragment = href.partition("#")
            if not fragment:
                continue
            if target.startswith(("http://", "https://", "mailto:")):
                continue  # external; this gate does not fetch
            fragment = unquote(fragment)
            dest = (f.parent / unquote(target)).resolve() if target else f.resolve()
            if dest.suffix != ".md":
                continue
            checked += 1
            rel = f.relative_to(root)
            if dest not in anchors:
                problems.append(f"{rel}: link to untracked or missing file {target}")
            elif fragment not in anchors[dest]:
                problems.append(f"{rel}: MISSING_ANCHOR #{fragment} in {target or f.name}")

    if problems:
        for p in problems:
            print(p, file=sys.stderr)
        print(f"\n{len(problems)} anchor problem(s) across {len(files)} files.", file=sys.stderr)
        return 1
    print(f"{checked} anchor link(s) across {len(files)} markdown files: all resolve.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
