#!/usr/bin/env python3
"""Regenerate scripts/_github_slugger_table.py from the real github-slugger.

Why this exists: the anchor gate needs to know which characters GitHub drops
when it builds a heading fragment. Two earlier attempts transcribed
github-slugger's character class by hand and both were wrong -- the first
collapsed whitespace runs, the second omitted the emoji and symbol ranges,
which made an ordinary `## Emoji 🚀 test` heading slug differently here than on
GitHub and let a broken link pass silently. The class is a generated 8KB
pattern with surrogate-pair alternations; reading it by eye is not a viable
strategy, so nothing here reads it.

Instead this asks the reference implementation directly: for every code point,
does github-slugger's own regex delete it? The answer set is emitted as ranges.
The vendored file is data produced by running the thing we are imitating, not
by interpreting it.

**This script always needs node and the network**: `generate()` runs
`npm install` unconditionally, including under `--check`. Run it when
deliberately moving to a new github-slugger version, and commit the
regenerated table with the version bump recorded below.

What each check can and cannot prove, because an earlier version of this
docstring got this wrong and claimed `--check` was an offline CI guard:

* `--check` (online, manual) regenerates from upstream and diffs. It is the
  **only** check here that can prove the committed table still matches
  github-slugger. CI does not run it, and cannot: there is no network
  contract for it, and an empty npm cache against an unreachable registry
  simply hangs.
* The offline guard is `tests/unit/test_check_doc_anchors.py`, which pins
  this file's sha256 and runs a 40-case differential frozen beside it. That
  proves the table has not drifted **since the corpus was frozen against
  it** -- it does not prove upstream fidelity, because both files live in
  this repository and a determined edit could update both together. Only the
  online `--check` closes that.

Usage: scripts/vendor_github_slugger.py [--version 2.0.0] [--check]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path

OUT = Path(__file__).resolve().parent / "_github_slugger_table.py"

ENUMERATE_JS = """
import {regex} from '%(pkg)s/regex.js';
const ranges = [];
let start = null;
for (let cp = 0; cp <= 0x10FFFF; cp++) {
  if (cp >= 0xD800 && cp <= 0xDFFF) {           // lone surrogates: not characters
    if (start !== null) { ranges.push([start, cp - 1]); start = null; }
    continue;
  }
  const removed = String.fromCodePoint(cp).replace(regex, '') === '';
  if (removed) { if (start === null) start = cp; }
  else if (start !== null) { ranges.push([start, cp - 1]); start = null; }
}
if (start !== null) ranges.push([start, 0x10FFFF]);
console.log(JSON.stringify(ranges));
"""


def generate(version: str) -> tuple[list[list[int]], dict[str, str]]:
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(
            ["npm", "install", "--prefix", tmp, f"github-slugger@{version}",
             "--silent", "--no-fund", "--no-audit"],
            check=True,
        )
        pkg = Path(tmp) / "node_modules" / "github-slugger"
        digests = {
            name: hashlib.sha256((pkg / name).read_bytes()).hexdigest()
            for name in ("regex.js", "index.js")
        }
        out = subprocess.run(
            ["node", "--input-type=module", "-e", ENUMERATE_JS % {"pkg": pkg}],
            check=True,
            capture_output=True,
            text=True,
        )
        return json.loads(out.stdout), digests


def render(version: str, ranges: list[list[int]], digests: dict[str, str]) -> str:
    body = "\n".join(f"    (0x{a:04X}, 0x{b:04X})," for a, b in ranges)
    return f'''"""Generated by scripts/vendor_github_slugger.py -- do not edit by hand.

Source: github-slugger {version}
  regex.js sha256 {digests["regex.js"]}
  index.js sha256 {digests["index.js"]}

Each pair is an inclusive code-point range that github-slugger's own regex
deletes. Produced by running that regex over every code point, not by reading
it: the published pattern is a generated 8KB class with surrogate-pair
alternations, and both previous hand transcriptions of it were wrong.

github-slugger's algorithm, from its index.js, is exactly three steps:
lowercase, delete every character in this set, then replace each remaining
space with a hyphen -- one per space, never per run.
"""

SLUGGER_VERSION = "{version}"
REGEX_JS_SHA256 = "{digests["regex.js"]}"
INDEX_JS_SHA256 = "{digests["index.js"]}"

REMOVED_RANGES: tuple[tuple[int, int], ...] = (
{body}
)
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", default="2.0.0")
    ap.add_argument(
        "--check",
        action="store_true",
        help="regenerate from upstream and diff (requires network; not a CI guard)",
    )
    args = ap.parse_args()

    ranges, digests = generate(args.version)
    rendered = render(args.version, ranges, digests)

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != rendered:
            print(
                f"{OUT.name} is out of date with github-slugger {args.version}; "
                "re-run scripts/vendor_github_slugger.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT.name} matches github-slugger {args.version}.")
        return 0

    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT} ({len(ranges)} ranges) from github-slugger {args.version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
